name: Pre-Merge Pipeline

on:
  pull_request:
    types:
      - opened
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: ls
        run: ls -la

      - name: cat
        run: cat README.md
